# Generated by Django 3.1.5 on 2021-01-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=128)),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
