# Generated by Django 3.1.5 on 2021-01-12 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='courts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courtname', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('numpart', models.IntegerField(default=2)),
                ('indoor', models.BooleanField()),
                ('std', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.courts')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partid', models.IntegerField()),
                ('day', models.DateTimeField(verbose_name='court_date')),
                ('slot1', models.BooleanField(default=False)),
                ('slot2', models.BooleanField(default=False)),
                ('slot3', models.BooleanField(default=False)),
                ('courtid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.courts')),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0)),
                ('courtid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.courts')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.orders')),
            ],
        ),
    ]
