# Generated by Django 3.1.5 on 2021-01-12 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courts',
            name='numpart',
        ),
        migrations.RemoveField(
            model_name='slots',
            name='partid',
        ),
        migrations.AddField(
            model_name='orders',
            name='slot_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='slotid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.slots'),
        ),
    ]
